import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 개발 참여(/contributing)의 목차. contributing/ 폴더 구조와 frontmatter의 sidebar_position으로 만든다.
const sidebars: SidebarsConfig = {
  contributingSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
