import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 사용 설명서(/guide)의 목차. guide/ 폴더 구조와 frontmatter의 sidebar_position으로 만든다.
const sidebars: SidebarsConfig = {
  guideSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
