import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 장애 대응(/incidents)의 목차. incidents/ 폴더 구조와 frontmatter의 sidebar_position으로 만든다.
const sidebars: SidebarsConfig = {
  incidentsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
